security:
    encoders:
        App\Entity\Admin:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Admin
                property: apikey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
              authenticators:
                - App\Security\TokenAuth

    access_control:
         - { path: ^/api, roles: ROLE_ADMIN }
